# Generated by Django 3.1.3 on 2020-12-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_national',
        ),
    ]
