# Generated by Django 3.1.3 on 2020-12-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_election_is_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_national',
            field=models.BooleanField(default=False),
        ),
    ]
