# Generated by Django 3.1.3 on 2020-12-04 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_election_is_national'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='is_national',
        ),
    ]
