# Generated by Django 3.1.3 on 2020-12-04 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('election_admin', 'Can Edit, Remove, and Add Elections'),)},
        ),
    ]
