# Generated by Django 3.1.4 on 2020-12-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201204_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
